# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-08-15 15:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='record',
            name='description',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='record',
            name='status',
            field=models.CharField(choices=[('Aprobado', 'Aprobado'), ('En revisión', 'En revisión')], default='En revisión', max_length=64, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='record',
            name='text',
            field=models.CharField(max_length=516, verbose_name='Texto'),
        ),
    ]
