# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-08-15 21:55
from __future__ import unicode_literals

import app.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20180815_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='audio',
            name='format',
            field=models.CharField(choices=[('mp3', 'mp3'), ('wav', 'wav'), ('flac', 'flac'), ('ogg', 'ogg')], default='mp3', max_length=16, verbose_name='Formato'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='audio',
            name='audio_file',
            field=models.FileField(null=True, upload_to=app.models.fileName),
        ),
        migrations.AlterField(
            model_name='audio',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audios', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='audio',
            name='text',
            field=models.CharField(max_length=512, verbose_name='Texto'),
        ),
    ]
